### PR TITLE
Add terraform examples for workshop

### PR DESCRIPTION
**Pull request by mmehrten**
*Description of changes:*

Add Terraform infrastructure as code to provision required infrastructure for MSK migration example with Kafka Connect. Provisions everything except for Docker images for Prometheus and Kafka Connect.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by awsalialem — CHANGES_REQUESTED** [review]
Could you please add, instructions in README.md which states:

1. How to run the TF template?
2. What resources TF creates?

**Comment by mmehrten** [comment]
Added a README to clarify the usage & resources created

**Comment by awsalialem** [comment]
I tested this branch and TF scripts. It appears that TF is attempting to create two MSK clusters. Since it takes a long time it eventually exits. I would request change in TF script to accept the broker address and auth credentials for both source / target clusters and build the replication pipeline.

**Review by awsalialem — APPROVED** [review]
LGTM

**Pull request merged**
